### ISSUE TITLE
Grotto Escape - game speed

### ISSUE THREAD

**Issue by DonDejvo** [AvinashPro/AvinashPro.github.io#1]
Hey, 

the game appears running too quickly on some devices.

I might have found the problem could be you forgot multiply velocity by delta time in following line:

[https://github.com/AvinashPro/AvinashPro.github.io/blob/main/files%2FGrotto%20Escape%2Fmain.js#L918](https://github.com/AvinashPro/AvinashPro.github.io/blob/main/files%2FGrotto%20Escape%2Fmain.js#L918)

**Comment by AvinashPro** [comment]
Hey David Dolejší Sir,

I tried to fix it, check it out if it is fixed now. I was kind of aware of this issue but I was lazy enough not to touch any code.


This might get personal message so feel free to ignore it:
I wanted to thank you. You were always there for me, whenever I needed help in learning something new. You were my inspiration. Even this game is highly inspired from your original "Grotto Escape" game. You made my learning days memorable. Thank you for everything. I can't even express in words how happy I am while writing this message to you. 

You are my hero!

**Comment by DonDejvo** [comment]
It might be OK now.

Anyway I was always glad to help you, not that I believe I did so much as you described, it was your hard work which moved you forward. I hope you keep working on yourself.
